name: Build & Push multi-arch Docker images

on:
  push:
    tags: [ '*.*.*' ]

env:
  VERSION_TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'dev' }}

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push ingrain-models image
        uses: docker/build-push-action@v5
        with:
          context: ./ingrain_model_server
          file: ./ingrain_model_server/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            owenpelliott/ingrain-models:latest
            owenpelliott/ingrain-models:${{ env.VERSION_TAG }}

      - name: Build & Push ingrain-inference image
        uses: docker/build-push-action@v5
        with:
          context: ./ingrain_inference_server
          file: ./ingrain_inference_server/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            owenpelliott/ingrain-inference:latest
            owenpelliott/ingrain-inference:${{ env.VERSION_TAG }}

      - name: Inspect pushed manifests
        run: |
          docker buildx imagetools inspect owenpelliott/ingrain-models:${{ env.VERSION_TAG }}
          docker buildx imagetools inspect owenpelliott/ingrain-inference:${{ env.VERSION_TAG }}
