name: Build & Push multi-arch image

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: owenpelliott/ingrain-server 

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.digest.outputs.value }} 

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & push linux/arm64 image
        env:
          TAG:   ${{ github.ref_name }}
          IMAGE: ${{ env.IMAGE_NAME }}
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t $IMAGE:latest-arm64 \
            -t $IMAGE:${TAG}-arm64 \
            --push .

      - id: digest
        env:
          TAG:   ${{ github.ref_name }}
          IMAGE: ${{ env.IMAGE_NAME }}
        run: |
          d=$(docker buildx imagetools inspect $IMAGE:${TAG}-arm64 \
               --format '{{ .Digest }}')
          echo "value=$d" >> "$GITHUB_OUTPUT"

  build-amd64:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.digest.outputs.value }}

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & push linux/amd64 image
        env:
          TAG:   ${{ github.ref_name }}
          IMAGE: ${{ env.IMAGE_NAME }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $IMAGE:latest-amd64 \
            -t $IMAGE:${TAG}-amd64 \
            --push .

      - id: digest
        env:
          TAG:   ${{ github.ref_name }}
          IMAGE: ${{ env.IMAGE_NAME }}
        run: |
          d=$(docker buildx imagetools inspect $IMAGE:${TAG}-amd64 \
               --format '{{ .Digest }}')
          echo "value=$d" >> "$GITHUB_OUTPUT"

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-arm64, build-amd64]

    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Create & push multi-arch manifest
        env:
          IMAGE:        ${{ env.IMAGE_NAME }}
          TAG:          ${{ github.ref_name }}
          ARM_DIGEST:   ${{ needs.build-arm64.outputs.digest }}
          AMD_DIGEST:   ${{ needs.build-amd64.outputs.digest }}
        run: |
          set -eux

          docker manifest rm $IMAGE:latest 2>/dev/null || true
          docker manifest rm $IMAGE:$TAG    2>/dev/null || true

          docker manifest create $IMAGE:latest \
            $IMAGE@${ARM_DIGEST} \
            $IMAGE@${AMD_DIGEST}

          docker manifest create $IMAGE:$TAG \
            $IMAGE@${ARM_DIGEST} \
            $IMAGE@${AMD_DIGEST}

          docker manifest push $IMAGE:latest
          docker manifest push $IMAGE:$TAG
