name: Build & Push multi-arch Docker images

on:
  push:
    tags:     [ '*.*.*' ]

env:
  IMAGE_NAME: owenpelliott/ingrain-server
  TAG: ${{ github.ref_type == 'tag' && github.ref_name || 'dev' }}

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & push images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.IMAGE_NAME }}:latest-amd64
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}-amd64
            ${{ env.IMAGE_NAME }}:latest-arm64
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}-arm64

      - name: Inspect manifest
        run: docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:${{ env.TAG }}
